### ISSUE TITLE
Applied value is too large for int representation on this CPU.

### ISSUE THREAD

**Issue by qarlosalberto** [smlgit/fpbinary#4]
Hi!

I'm having this problem:

```{python}
>>> fp_num = FpBinary(int_bits=0, frac_bits=15, signed=True, value=-0.501)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Applied value is too large for int representation on this CPU.
```

My CPU is **Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz**

**Comment by smlgit** [comment]
Hi,

You are using a signed value without any int bits. FpBinary uses 2's complement representation. For example, -0.5 = -1 + 0.5 which, in binary is 1.10000...

So, if you are using values that are negative, you need at least one int bit because that is where the sign comes from.

Try adding an int bit and let me know.
sml

**Comment by smlgit** [comment]
Actually, on further thought, you may be right - there is something up with the magnitude checking on construction, and the value should probably be saturated by default anyway. Let me take a look and thanks for pointing it out.

**Comment by smlgit** [comment]
There were two issues here:

1. When instances of FpBinary are created that require less than the number of platform bits (i.e. instantiating _FpBinarySmall under the hood), a check was made to ensure a cast from the initializing float to the platform (long long) won't overflow. If an overflow would occur, an exception was always raised. This is incorrect because the overflow mode on a create call is 'saturate'. I changed the code to always saturate to the platform bit limitation before checking for overflow on the basis of (int_bits, frac_bits).

2. Even given the issue in (1), an issue should not have been seen with the example case because the input value had a smaller magnitude than the system max. The original code was using the number of bits specified by the user instead of the system bit length for this initial overflow check. This was fixed as a consequence of fixing issue (1).

A test was added to verify that saturation is applied when creating an FpBinary instance with a float or int as the initializing value.
