### ISSUE TITLE
Creating np.array of FpBinary triggers cast to bool 

### ISSUE THREAD

**Issue by baileyji** [smlgit/fpbinary#9]
I've been using the function below to generate arrays of FpBinary numbers. It works, but is a bit slower than it could be as unless I use the for loop all of the FpBinary numbers get cast to bool (see the commented lines).

An simpler example is to look at the result of 

```
gen=lambda x: FpBinary(int_bits=1, frac_bits=15, signed=True, value=x)
np.array([FP16_15(.4)],  dtype=object)
```
It looks like the FpBinary object is getting expanded into its bits!

I'm not sure what would work useres of this library. I do find I'm generating large numpy arrays of FP numbers (100k-a few million). 

```
def fparray(a, fpgen=None):
    """
    Convert a numpy array to a numpy object array of FpBinary numbers.

    Complex numbers gain an additional axis of length 2.

    if fpgen is None 16wide  1integer signed is used
    """
    if fpgen is None:
        fpgen = lambda x: FpBinary(int_bits=1, frac_bits=15, signed=True, value=x)

    if a.dtype in (np.complex, np.complex128, np.complex64):
        out = np.empty(tuple(list(a.shape)+[2]), dtype=object)
        b = [(fpgen(x.real), fpgen(x.imag)) for x in a.flat]
        for i in range(out.size):
            out.flat[i] = b[i//2][i % 2]
        #You'd think this would work, but it doesn't as the FP types get cast to bool
        #out.flat = [(fpgen(x.real), fpgen(x.imag)) for x in a.flat]
    else:
        out = np.empty_like(a, dtype=object)
        b = [fpgen(x) for x in a.flat]
        for i in range(out.size):
            out.flat[i] = b[i]
        #out.flat = [fpgen(x) for x in a.flat]
    return out
```

**Comment by smlgit** [comment]
Hi Jeb,

I suspect the reason this happens is because I implemented the sequence operations and an sq_item call returns a bool to indicate if the bit is high or low (i.e. it is a shorthand to view the number as a bitfield). I think if numpy sees that an object can be interpreted as a sequence, it has no choice but to expand out the "array", which will give you a bunch of bools.

I wanted the access of individual bits to be intuitive and feel like slv bit access, hence the use of the sequence methods, and i also use slicing notation to produce new numbers from parts of an fpbinary bitfield. But I have actually been considering how one would use fpbinary with numpy and am aware that I may have to change this. I'll have a look at numpy and see what makes sense.

**Comment by smlgit** [comment]
I noticed that there is an issue raised regarding this numpy behavior: https://github.com/numpy/numpy/issues/5933.

The code that sets the array .flat attribute creates an ndarray from the list that you pass and then creates an iterator from that. The ndarray creation drills right down into the bits of the FpBinary instance.

You could try to work around this by controlling the array creation by starting with a flat array and then returning a reshaped array:

```
out = np.empty((a.size,), dtype=object)
out[:] = [fpgen(x) for x in a.flat]
return out.reshape(a.shape)
``` 

I think this should be about the same speed as your desired code. The code for the complex case would use the new shape tuple with the extra dims. Let me know if it is suitable.

**Comment by smlgit** [comment]
Fixed on branch numpy_support.
